stages:
  - build

build:
  stage: build
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  script:
    - docker buildx build --platform=linux/amd64 --push --progress=plain -t ${CI_REGISTRY_IMAGE}:latest .
