apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: node-app
spec:
  selector:
    matchLabels:
      name: node-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        name: node-app
    spec:
      containers:
        - name: dashboard
          imagePullPolicy: Always
          image: registry.gitlab.com/team-la-bamba/dashboard:latest
          ports:
            - containerPort: 81
              name: dashboard
          resources:
            limits:
              memory: 256Mi
              cpu: 150m
        - name: app
          imagePullPolicy: Always
          image: registry.gitlab.com/team-la-bamba/poll-app:latest
          ports:
            - containerPort: 80
              name: web-app
          resources:
            limits:
              memory: 256Mi
              cpu: 150m
        - name: api
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: connection_string
          imagePullPolicy: Always
          image: registry.gitlab.com/team-la-bamba/api:latest
          ports:
            - containerPort: 3000
              name: web-api
          resources:
            limits:
              memory: 256Mi
              cpu: 150m
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: default
spec:
  selector:
    name: node-app
  ports:
    - port: 3000
      targetPort: 3000
      name: api-http
    - port: 80
      targetPort: 80
      name: app-http
    - port: 81
      targetPort: 81
      name: dashboard-http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ing
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: dashboard.labamba.space
      http:
        paths:
          - backend:
              serviceName: api-svc
              servicePort: 81
    - host: app.labamba.space
      http:
        paths:
          - backend:
              serviceName: api-svc
              servicePort: 80
    - host: api.labamba.space
      http:
        paths:
          - backend:
              serviceName: api-svc
              servicePort: 3000
